#ifndef DEFS_H
#define DEFS_H

#define MAX_CONNECTION_SIZE 256
#define MAX_WAITING_QUEUE 256
#define MAX_BUFFER_SIZE 1024
#define MAX_RECV_SIZE MAX_BUFFER_SIZE
#define MAX_SEND_SIZE MAX_BUFFER_SIZE
#define SESSION_BUFFER_CAPACITY 2048

typedef char u8;

#endif